version: '3.8'

services:
  vpn-browser-backend:
    build: .
    container_name: vpn-browser-backend
    ports:
      - "3000:3000"
    volumes:
      - ./database:/app/database
      - ./logs:/app/logs
    environment:
      - NODE_ENV=production
      - PORT=3000
      - JWT_SECRET=vpn-browser-secret-key-2024-production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
